default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  timeout: 5000

development:
  <<: *default
  database: simple-api-develop

test:
  <<: *default
  database: simple-api-test

production:
  <<: *default
  database: simple-api-production
  username: root
  password: <%= ENV['PRODUCTION_PASSWORD'] %>