# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50be43d0563c108a463879758d08a63a4c303af39e25538e2e77b1fad03df3d23a9ff572b606c4908de7be30687ac386a1d82c1db6cb80c4f126b246d7824d89

test:
  secret_key_base: 6e5a0509e5afedcdc02e9124abd71745c5c6b8b6624cde94c5030c756335efa7e026761c65ef9c9ace06bf9633920f40ce03558d44fae7d030458598baac7b78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
